"""users table migration switching back to dev env

Revision ID: 3aa23bbdb39e
Revises: 324a0cfdc9a2
Create Date: 2024-03-16 11:59:18.967418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa23bbdb39e'
down_revision: Union[str, None] = '324a0cfdc9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
