"""added tablename to users table

Revision ID: b58e8dc8a07c
Revises: 9f6e5a40dcab
Create Date: 2024-01-27 16:07:12.634462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58e8dc8a07c'
down_revision: Union[str, None] = '9f6e5a40dcab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
