"""Recreate users table

Revision ID: c0ef0fb95ebe
Revises: 3aa23bbdb39e
Create Date: 2024-03-16 14:07:39.535904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ef0fb95ebe'
down_revision: Union[str, None] = '3aa23bbdb39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
